### ISSUE TITLE
Images with transparent background (PNG)

### ISSUE THREAD

**Issue by seltix5** [gschoppe/PHP-Smart-Crop#2]
hello!

Great job with this class!

I found out today the get_resized function will return a black background image when manipulating a PNG image with transparent background, as a workaround I added this :

get_resized() :
```
        // make the final cropped image
        $croppedThumb = imagecreatetruecolor($newW,$newH);
        + imagealphablending( $croppedThumb, false );
        + imagesavealpha( $croppedThumb, true );
        imagecopyresampled($croppedThumb, $temp, 0, 0, $x, $y, $newW, $newH, $newW, $newH);
        imagedestroy($temp);
        return($croppedThumb);
```

rough_in_size() :
```
        // make the resized image
        $temp = imagecreatetruecolor($tempW, $tempH);
        + imagealphablending( $temp, false );
        + imagesavealpha( $temp, true );
        imagecopyresampled($temp, $this->img, 0, 0, 0, 0, $tempW, $tempH, $w, $h);
        return($temp);
```

do you think this is the best option?
should it check before if it is a PNG and only add this options if it is?

thanks!

**Comment by gschoppe** [comment]
it shouldn't be an issue to run this code on all image types, as any GD truecolor image has an alpha channel, it's just empty for jpegs and the like.

Would you be willing to submit a pull request for this change? I'll merge it in for anyone who runs across this in the future.

**Comment by seltix5** [comment]
Hey,
Sure, I will do it later =)

**Comment by gschoppe** [comment]
merged! thanks for the PR

**Comment by seltix5** [comment]
np =)
