### ISSUE TITLE
find_focus() -> imagedestroy($temp)

### ISSUE THREAD

**Issue by mjau-mjau** [gschoppe/PHP-Smart-Crop#7]
In the `find_focus()` function, shouldn't `imagedestroy($temp)` be called at the end of the function? It seems perhaps this has minimal effect for a small `$temp` image, but I'm working on some memory-estimation functionality, and since Smart-Crop uses slightly more memory than a basic center-crop, I am trying to locate where memory goes.

Great script!

**Comment by gschoppe** [comment]
You are correct.  Theoretically `$temp` should be automatically released for garbage collection when it passes out of scope, but since GD functions are a thin wrapper around C code, it's probably a good idea to manually release the memory, just in case.

I just committed a fix.
